require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.0
  UseCache: true
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/**/*"
    - "lib/tasks/*"
    - "app/channels/**/*"
    - "vendor/**/*"
    - "path/ruby"
    - "bundle/**/*"
    - "node_modules/**/*"
    - "config.ru"
    - "Rakefile"
    - "rails.rb"

Bundler/OrderedGems:
  Enabled: true
Metrics/CyclomaticComplexity:
  Max: 6
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Rails/Date:
  Enabled: true
  EnforcedStyle: strict
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: true
  Whitelist: [touch, increment!, decrement!]
Style/IdenticalConditionalBranches:
  Enabled: false
Style/AndOr:
  Enabled: true
Style/MultilineIfModifier:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
